# Generated by Django 3.1.3 on 2023-07-29 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 3, 36, 9, 435919, tzinfo=utc)),
        ),
    ]
