# Generated by Django 3.1.3 on 2023-07-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_learner_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='dob',
            field=models.DateField(default='now'),
        ),
    ]
