# Generated by Django 3.1.3 on 2023-07-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20230729_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='about',
            field=models.CharField(default='about', max_length=100),
        ),
    ]
