# Generated by Django 3.1.3 on 2023-08-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_auto_20230802_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='question_ids',
            field=models.CharField(default='', max_length=200),
        ),
    ]
