# Generated by Django 3.1.3 on 2023-08-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0009_submission_question_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='question_ids',
        ),
    ]
